const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Plugins.Touch,
		C3.Plugins.Arr,
		C3.Plugins.Function,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Plugins.LocalStorage,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Cnds.PickNth,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Function.Exps.Param,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.System.Acts.SetFullscreenQuality,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Type: 0},
	{Platform: 0},
	{Solid: 0},
	{Elements: 0},
	{Array: 0},
	{Active: 0},
	{Line: 0},
	{Ground: 0},
	{Function: 0},
	{Background: 0},
	{Audio: 0},
	{Bullet: 0},
	{Sine: 0},
	{UpScore: 0},
	{Particles: 0},
	{Score: 0},
	{LevelText: 0},
	{TimeBar: 0},
	{Bar: 0},
	{MenuButton: 0},
	{PlayButton: 0},
	{SoundButton: 0},
	{Rotate: 0},
	{Rays: 0},
	{LocalStorage: 0},
	{Best: 0},
	{CloseButton: 0},
	{TimeBarLine: 0},
	{ProgressBar: 0},
	{ProgressSlodeBar: 0},
	{ProgressBack: 0},
	{Background2: 0},
	{Promo: 0},
	{loadingbar: 0},
	{loadingvalue: 0},
	{TiledBackground2: 0},
	{loader: 0},
	{TradicinKids2MadeWithPosterMyWall: 0},
	{TradicionSalsaGuy: 0},
	{Sprite: 0},
	{TradicinKids2MadeWithPosterMyWall2: 0},
	{LEVEL: 0},
	{FRAMES: 0},
	{AllTime: 0},
	{HighScore: 0},
	{Timer: 0},
	{CellY: 0},
	{CellX: 0},
	{LINE: 0},
	{Loop: 0},
	{i: 0},
	{StartY: 0},
	{StartX: 0},
	{X: 0},
	{Y: 0},
	{LocalScore: 0},
	{PointsNeed: 0},
	{PointsNow: 0},
	{i2: 0}
];

self.InstanceType = {
	Elements: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Array: class extends self.IArrayInstance {},
	Line: class extends self.ISpriteInstance {},
	Ground: class extends self.ISpriteInstance {},
	Function: class extends self.IInstance {},
	Background: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	UpScore: class extends self.ISpriteFontInstance {},
	Particles: class extends self.IParticlesInstance {},
	Score: class extends self.ISpriteFontInstance {},
	LevelText: class extends self.ISpriteFontInstance {},
	TimeBar: class extends self.ISpriteInstance {},
	Bar: class extends self.ISpriteInstance {},
	MenuButton: class extends self.ISpriteInstance {},
	PlayButton: class extends self.ISpriteInstance {},
	SoundButton: class extends self.ISpriteInstance {},
	Rays: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Best: class extends self.ISpriteFontInstance {},
	CloseButton: class extends self.ISpriteInstance {},
	TimeBarLine: class extends self.ISpriteInstance {},
	ProgressBar: class extends self.ISpriteInstance {},
	ProgressSlodeBar: class extends self.ISpriteInstance {},
	ProgressBack: class extends self.ISpriteInstance {},
	Background2: class extends self.ISpriteInstance {},
	Promo: class extends self.ISpriteInstance {},
	loadingbar: class extends self.ITiledBackgroundInstance {},
	loadingvalue: class extends self.ITextInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	loader: class extends self.ITextInstance {},
	TradicinKids2MadeWithPosterMyWall: class extends self.ISpriteInstance {},
	TradicionSalsaGuy: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TradicinKids2MadeWithPosterMyWall2: class extends self.ISpriteInstance {}
}